# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15890e8f374d2218e16dc1faf395058f4b8dfbd2ddcc3dc073d64bad79f4b088a96130ac8878ccbcdb95f67247561c32974d0b61a0dac0511a4b7e6719e6b96f

test:
  secret_key_base: c8d3211fcbb6171db8acffe96acc990488e133ea7b0843946d53ca27fbfe736d1f7a7f72c956ff5f36aa1dfa6470fb33a3c2a16be025d1d2aad0db365e660a73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
